public enum SemanticErrorType {
    UNDEF_TYPE,
    UNDEF_VAR,
    UNDEF_FUNC,
    REDEF_VAR,
    REDEF_FUNC,
    MISMATCH_ASSIGN,
    MISMATCH_OPERANDS,
    MISMATCH_RETURN,
    FUNC_PARAM,
    NOT_ARRAY,
    NOT_FUNC,
}
